### ISSUE TITLE
Rupture + Stylus + Lost (using cycles)

### ISSUE THREAD

**Issue by maxisix** [corysimmons/lost#58] opened 2015-04-07 23:42 UTC
I have a problem using Rupture and Lost only when i use cycles. Its working if i use @media but when i use rupture its not working correctly. If i use Rupture without cycles its working well. Could be nice to have your own rupture with lost ;)

**Comment by corysimmons** [comment] 2015-04-08 01:19
@maxisix Can you send me the code that causes this error?

**Comment by flip4bytes** [comment] 2015-04-08 06:40
Rupture + Stylus + Lost works totally fine for me. The newer version of Lost Grid doesn't even use cycles anymore, it just does it automatically. If you aren't too heavily invested, I recommend just updating to the newest version.

**Comment by corysimmons** [comment] 2015-04-08 08:21
@flip4bytes It kind of uses `$cycle` still - it just picks the denominator by default.

**Comment by corysimmons** [comment] 2015-04-08 08:28
Closing this as I can't reproduce it. @maxisix Send me code and I'll help you figure it out.

![Working](http://i.imgur.com/ZpCnBq6.gif)

**Closed by corysimmons** 2015-04-08 08:28 UTC

**Comment by maxisix** [comment] 2015-04-08 14:16
Found the problem it was because of gulp-group-css-media-queries ! :/

**Comment by corysimmons** [comment] 2015-04-08 17:18
Ah I see. Weird. Thanks for letting us know. =)
